# Welcome to my GitHub configuration file!
# A minimalistic and clean approach to settings

# Repository settings
name: My Cool Project
description: |
  A simple but aesthetically pleasing project for all your needs.
  A beautiful repository for developers who love clean code.

# Maintain repository's default branch
default_branch: main

# Set the repository visibility (private or public)
visibility: public

# Create custom labels to make your issues and pull requests more organized
labels:
  - bug
  - feature
  - enhancement
  - documentation
  - help wanted

# Actions and workflows
workflows:
  # Build & Test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
